# Docker Compose configuration for development environment

services:
  web:
    restart: "always"
    build:
      context: .
      target: prod
    image: jc-groups-manager-prod
    container_name: web
    ports:
      - "5050:5050"
    networks:
      - default

  worker:
    restart: "always"
    build:
      context: .
      target: prod
    image: jc-groups-manager-prod
    container_name: worker
    command: "/usr/bin/supervisord -c supervisord.worker.conf"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - default


  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      target: prod
    image: jc-groups-manager-nginx-prod
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - default

  postgres:
    restart: "always"
    image: postgres:12
    environment:
      POSTGRES_USER: jcgroups
      POSTGRES_DB: jcgroups
      POSTGRES_PASSWORD: jcpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  redis:
    restart: "always"
    image: redis:7.4.1
    ports:
      - "6379:6379"
    networks:
      - default

  rabbitmq:
    restart: "always"
    image: rabbitmq:4.0.2
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit consumer_timeout 10800000"

volumes:
  pgdata:

networks:
  default:
    external: true
    name: jairocloud-groups-manager_default
